# to activate this action, move it to .github/workflows and
# specify the path to your project on line 23

name: CD laravel

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and execute all tasks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/your-app
            
            # Down Docker
            docker compose down
            
            # Pull changes from repo
            git pull origin master
            
            # Up & build containers
            docker compose up -d --build
            
            # Install PHP dependencies
            docker compose run --rm composer install --no-dev --optimize-autoloader
            
            # Run migrations
            docker compose run --rm artisan migrate --force
            
            # Cache configuration
            docker compose run --rm artisan config:clear
            docker compose run --rm artisan config:cache
            docker compose run --rm artisan route:cache
            docker compose run --rm artisan event:cache
            docker compose run --rm artisan view:cache
      
            # Install JS dependencies & build assets
            docker compose exec php sh -c "npm i && npm run build"
